name: Snyk scan GH Action
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    container:
      image: gh_test:v1.0
    steps:
    - name: Run Snyk to check Docker image for vulnerabilities
      uses: actions/checkout@v3
      env:
        SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}